### ISSUE TITLE
A minimum example? 

### ISSUE THREAD

**Issue by unnir** [RylonW/DocNLC#1]
Dear Authors, 

Thank you for publishing your code base and sharing the weights. Would it be possible to create a short tutorial on how to use it for a given sample?

**Comment by RylonW** [comment]
Sure! Thank you for proposing the problem. I will update config.yaml for training and testing!

**Comment by RylonW** [comment]
Hey unnir! I just updated the test steps. Just give it a try! If you have any other problems, I'm happy to check and help!

**Comment by kerberosargos** [comment]
@unnir  Hello, may be this post [#2 ](https://github.com/RylonW/DocNLC/issues/2)can help you

**Comment by RylonW** [comment]
Refer to kerberosargos's example
